#!/bin/bash
#
# send_command: sends a Moneta command to the docker containers running
#
# Use the command without options to show the help section
#
# Copyright (c) 2021 Michael Montuori
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ "$1" == "" ]; then
	echo "usage: `basename $0` {all|container ID} {command}"
	exit 1
fi

if [ "$1" == "all" ]; then
	node=""
else
	node=${1}
fi

cnt=0
cmd_string=""
for cmd in ${*}; do
	if [ "$cnt" == "0" ]; then
		cnt=`expr $cnt + 1`
		continue
	fi
	cmd_string="${cmd_string} ${cmd}"
done

for i in $(docker ps | grep mnta-env | grep "$node" | awk '{ print $1 }'); do
	echo "***************************************************************************"
       	echo -n "${i}: ";
       	docker exec $i /moneta/src/moneta-cli ${cmd_string};
	echo "***************************************************************************"
done
